// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystem.Data.Models;

public partial class CustomerService
{
    public int Id { get; set; }

    public int? CustomerId { get; set; }

    public int? TravelId { get; set; }

    public int? NumberOfPerson { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual Travel Travel { get; set; }
}