// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystem.Data.Models;

public partial class Delivery
{
    public int Id { get; set; }

    public int? KoiOrderId { get; set; }

    public int? DeliveryStaffId { get; set; }

    public string Code { get; set; }

    public string RecipientName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public decimal? RemainingPayment { get; set; }

    public bool? PaymentReceived { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string Note { get; set; }

    public string DeliveryStatus { get; set; }

    public virtual KoiOrder KoiOrder { get; set; }
}