// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace KoiOrderingSystem.Data.Models;

public partial class FA24_SE1717_PRN231_G3_KOIORDERINGSYSTEMINJAPANContext : DbContext
{
    public FA24_SE1717_PRN231_G3_KOIORDERINGSYSTEMINJAPANContext()
    {
    }

    public FA24_SE1717_PRN231_G3_KOIORDERINGSYSTEMINJAPANContext(DbContextOptions<FA24_SE1717_PRN231_G3_KOIORDERINGSYSTEMINJAPANContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CustomerService> CustomerServices { get; set; }

    public virtual DbSet<Delivery> Deliveries { get; set; }

    public virtual DbSet<DeliveryDetail> DeliveryDetails { get; set; }

    public virtual DbSet<Farm> Farms { get; set; }

    public virtual DbSet<FarmCategory> FarmCategories { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<KoiFish> KoiFishes { get; set; }

    public virtual DbSet<KoiOrder> KoiOrders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceOrder> ServiceOrders { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<Travel> Travels { get; set; }

    public virtual DbSet<TravelFarm> TravelFarms { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=FA24_SE1717_PRN231_G3_KOIORDERINGSYSTEMINJAPAN;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<CustomerService>(entity =>
        {
            entity.ToTable("CustomerService");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Status).IsRequired();

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerServices).HasForeignKey(d => d.CustomerId);

            entity.HasOne(d => d.Travel).WithMany(p => p.CustomerServices).HasForeignKey(d => d.TravelId);
        });

        modelBuilder.Entity<Delivery>(entity =>
        {
            entity.ToTable("Delivery");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.DeliveryStaff).WithMany(p => p.Deliveries).HasForeignKey(d => d.DeliveryStaffId);

            entity.HasOne(d => d.KoiOrder).WithOne(p => p.Delivery).HasForeignKey<Delivery>(d => d.KoiOrderId);
        });

        modelBuilder.Entity<DeliveryDetail>(entity =>
        {
            entity.ToTable("DeliveryDetail");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Delivery).WithMany(p => p.DeliveryDetails).HasForeignKey(d => d.DeliveryId);
        });

        modelBuilder.Entity<Farm>(entity =>
        {
            entity.ToTable("Farm");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        modelBuilder.Entity<FarmCategory>(entity =>
        {
            entity.HasKey(e => new { e.FarmId, e.CategoryId });

            entity.ToTable("FarmCategory");

            entity.HasOne(d => d.Category).WithMany(p => p.FarmCategories)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Farm).WithMany(p => p.FarmCategories)
                .HasForeignKey(d => d.FarmId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.ToTable("Invoice");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<KoiFish>(entity =>
        {
            entity.ToTable("KoiFish");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Gender).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Category).WithMany(p => p.KoiFishes).HasForeignKey(d => d.CategoryId);
        });

        modelBuilder.Entity<KoiOrder>(entity =>
        {
            entity.ToTable("KoiOrder");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Customer).WithMany(p => p.KoiOrders).HasForeignKey(d => d.CustomerId);

            entity.HasOne(d => d.Invoice).WithOne(p => p.KoiOrder).HasForeignKey<KoiOrder>(d => d.InvoiceId);
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.ToTable("OrderDetail");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.KoiFish).WithMany(p => p.OrderDetails).HasForeignKey(d => d.KoiFishId);

            entity.HasOne(d => d.KoiOrder).WithMany(p => p.OrderDetails).HasForeignKey(d => d.KoiOrderId);
        });

        modelBuilder.Entity<Sale>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Status).IsRequired();
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.CustomerService).WithOne(p => p.Sale).HasForeignKey<Sale>(d => d.CustomerServiceId);

            entity.HasOne(d => d.SaleStaff).WithMany(p => p.Sales).HasForeignKey(d => d.SaleStaffId);
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.ToTable("Service");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasMany(d => d.CustomerServices).WithMany(p => p.Services)
                .UsingEntity<Dictionary<string, object>>(
                    "ServiceXcustomerService",
                    r => r.HasOne<CustomerService>().WithMany()
                        .HasForeignKey("CustomerServiceId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Service>().WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("ServiceId", "CustomerServiceId");
                        j.ToTable("ServiceXCustomerService");
                        j.HasIndex(new[] { "CustomerServiceId" }, "IX_ServiceXCustomerService_CustomerServiceId");
                    });
        });

        modelBuilder.Entity<ServiceOrder>(entity =>
        {
            entity.ToTable("ServiceOrder");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.CustomerService).WithMany(p => p.ServiceOrders).HasForeignKey(d => d.CustomerServiceId);

            entity.HasOne(d => d.Invoice).WithOne(p => p.ServiceOrder).HasForeignKey<ServiceOrder>(d => d.InvoiceId);
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.ToTable("Size");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.SizeInCm).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SizeInGram).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.KoiFish).WithOne(p => p.Size).HasForeignKey<Size>(d => d.KoiFishId);
        });

        modelBuilder.Entity<Travel>(entity =>
        {
            entity.ToTable("Travel");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TravelFarm>(entity =>
        {
            entity.HasKey(e => new { e.TravelId, e.FarmId });

            entity.ToTable("TravelFarm");

            entity.HasOne(d => d.Farm).WithMany(p => p.TravelFarms)
                .HasForeignKey(d => d.FarmId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Travel).WithMany(p => p.TravelFarms)
                .HasForeignKey(d => d.TravelId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Gender).IsRequired();
            entity.Property(e => e.Role).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}