// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystem.Data.Models;

public partial class KoiFish
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public int? SizeId { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public DateTime? Dob { get; set; }

    public string Gender { get; set; }

    public string Origin { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string Note { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Size Size { get; set; }
}