// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiOrderingSystem.Data.Models;

public partial class Sale
{
    public int Id { get; set; }

    public int? CustomerServiceId { get; set; }

    public int? SaleStaffId { get; set; }

    public decimal? TotalPrice { get; set; }

    public string ProposalDetails { get; set; }

    public string ApprovalStatus { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual CustomerService CustomerService { get; set; }
}